// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.1
// source: api/service.proto

package servicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackendRuntime_Invoke_FullMethodName = "/service.v1.BackendRuntime/Invoke"
)

// BackendRuntimeClient is the client API for BackendRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendRuntimeClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
}

type backendRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendRuntimeClient(cc grpc.ClientConnInterface) BackendRuntimeClient {
	return &backendRuntimeClient{cc}
}

func (c *backendRuntimeClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, BackendRuntime_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendRuntimeServer is the server API for BackendRuntime service.
// All implementations must embed UnimplementedBackendRuntimeServer
// for forward compatibility.
type BackendRuntimeServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	mustEmbedUnimplementedBackendRuntimeServer()
}

// UnimplementedBackendRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackendRuntimeServer struct{}

func (UnimplementedBackendRuntimeServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedBackendRuntimeServer) mustEmbedUnimplementedBackendRuntimeServer() {}
func (UnimplementedBackendRuntimeServer) testEmbeddedByValue()                        {}

// UnsafeBackendRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendRuntimeServer will
// result in compilation errors.
type UnsafeBackendRuntimeServer interface {
	mustEmbedUnimplementedBackendRuntimeServer()
}

func RegisterBackendRuntimeServer(s grpc.ServiceRegistrar, srv BackendRuntimeServer) {
	// If the following call panics, it indicates UnimplementedBackendRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackendRuntime_ServiceDesc, srv)
}

func _BackendRuntime_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendRuntimeServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendRuntime_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendRuntimeServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackendRuntime_ServiceDesc is the grpc.ServiceDesc for BackendRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.v1.BackendRuntime",
	HandlerType: (*BackendRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _BackendRuntime_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/service.proto",
}
