// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: api/service.proto

package servicev1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	BackendRuntime_Invoke_FullMethodName = "/service.v1.BackendRuntime/Invoke"
)

type BackendRuntimeClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
}

type backendRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendRuntimeClient(cc grpc.ClientConnInterface) BackendRuntimeClient {
	return &backendRuntimeClient{cc}
}

func (c *backendRuntimeClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, BackendRuntime_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type BackendRuntimeServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	mustEmbedUnimplementedBackendRuntimeServer()
}

type UnimplementedBackendRuntimeServer struct{}

func (UnimplementedBackendRuntimeServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedBackendRuntimeServer) mustEmbedUnimplementedBackendRuntimeServer() {}
func (UnimplementedBackendRuntimeServer) testEmbeddedByValue()                        {}

type UnsafeBackendRuntimeServer interface {
	mustEmbedUnimplementedBackendRuntimeServer()
}

func RegisterBackendRuntimeServer(s grpc.ServiceRegistrar, srv BackendRuntimeServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackendRuntime_ServiceDesc, srv)
}

func _BackendRuntime_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendRuntimeServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendRuntime_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendRuntimeServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var BackendRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.v1.BackendRuntime",
	HandlerType: (*BackendRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _BackendRuntime_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/service.proto",
}
