// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: api/service.proto

package servicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubjectType int32

const (
	SubjectType_SUBJECT_TYPE_UNSPECIFIED     SubjectType = 0
	SubjectType_SUBJECT_TYPE_USER            SubjectType = 1
	SubjectType_SUBJECT_TYPE_SERVICE_ACCOUNT SubjectType = 2
	SubjectType_SUBJECT_TYPE_SYSTEM          SubjectType = 3
	SubjectType_SUBJECT_TYPE_ANONYMOUS       SubjectType = 4
)

// Enum value maps for SubjectType.
var (
	SubjectType_name = map[int32]string{
		0: "SUBJECT_TYPE_UNSPECIFIED",
		1: "SUBJECT_TYPE_USER",
		2: "SUBJECT_TYPE_SERVICE_ACCOUNT",
		3: "SUBJECT_TYPE_SYSTEM",
		4: "SUBJECT_TYPE_ANONYMOUS",
	}
	SubjectType_value = map[string]int32{
		"SUBJECT_TYPE_UNSPECIFIED":     0,
		"SUBJECT_TYPE_USER":            1,
		"SUBJECT_TYPE_SERVICE_ACCOUNT": 2,
		"SUBJECT_TYPE_SYSTEM":          3,
		"SUBJECT_TYPE_ANONYMOUS":       4,
	}
)

func (x SubjectType) Enum() *SubjectType {
	p := new(SubjectType)
	*p = x
	return p
}

func (x SubjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_service_proto_enumTypes[0].Descriptor()
}

func (SubjectType) Type() protoreflect.EnumType {
	return &file_api_service_proto_enumTypes[0]
}

func (x SubjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubjectType.Descriptor instead.
func (SubjectType) EnumDescriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{0}
}

type PermissionEffect int32

const (
	PermissionEffect_PERMISSION_EFFECT_UNSPECIFIED PermissionEffect = 0
	PermissionEffect_PERMISSION_EFFECT_ALLOW       PermissionEffect = 1
	PermissionEffect_PERMISSION_EFFECT_DENY        PermissionEffect = 2
)

// Enum value maps for PermissionEffect.
var (
	PermissionEffect_name = map[int32]string{
		0: "PERMISSION_EFFECT_UNSPECIFIED",
		1: "PERMISSION_EFFECT_ALLOW",
		2: "PERMISSION_EFFECT_DENY",
	}
	PermissionEffect_value = map[string]int32{
		"PERMISSION_EFFECT_UNSPECIFIED": 0,
		"PERMISSION_EFFECT_ALLOW":       1,
		"PERMISSION_EFFECT_DENY":        2,
	}
)

func (x PermissionEffect) Enum() *PermissionEffect {
	p := new(PermissionEffect)
	*p = x
	return p
}

func (x PermissionEffect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionEffect) Descriptor() protoreflect.EnumDescriptor {
	return file_api_service_proto_enumTypes[1].Descriptor()
}

func (PermissionEffect) Type() protoreflect.EnumType {
	return &file_api_service_proto_enumTypes[1]
}

func (x PermissionEffect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionEffect.Descriptor instead.
func (PermissionEffect) EnumDescriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{1}
}

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Caller        *CallerContext         `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Payload       *Payload               `protobuf:"bytes,3,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	Attributes    *Attributes            `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_api_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *InvokeRequest) GetCaller() *CallerContext {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *InvokeRequest) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeRequest) GetAttributes() *Attributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_api_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{1}
}

func (x *Operation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CallerContext struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SubjectId        string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType      SubjectType            `protobuf:"varint,2,opt,name=subject_type,json=subjectType,proto3,enum=service.v1.SubjectType" json:"subject_type,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	GroupIds         []string               `protobuf:"bytes,4,rep,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	Grants           []*PermissionGrant     `protobuf:"bytes,5,rep,name=grants,proto3" json:"grants,omitempty"`
	AuthenticationId *string                `protobuf:"bytes,6,opt,name=authentication_id,json=authenticationId,proto3,oneof" json:"authentication_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallerContext) Reset() {
	*x = CallerContext{}
	mi := &file_api_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallerContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallerContext) ProtoMessage() {}

func (x *CallerContext) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallerContext.ProtoReflect.Descriptor instead.
func (*CallerContext) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{2}
}

func (x *CallerContext) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CallerContext) GetSubjectType() SubjectType {
	if x != nil {
		return x.SubjectType
	}
	return SubjectType_SUBJECT_TYPE_UNSPECIFIED
}

func (x *CallerContext) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CallerContext) GetGroupIds() []string {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

func (x *CallerContext) GetGrants() []*PermissionGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *CallerContext) GetAuthenticationId() string {
	if x != nil && x.AuthenticationId != nil {
		return *x.AuthenticationId
	}
	return ""
}

type PermissionGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *PermissionTarget      `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Scope         *PermissionScope       `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Effect        PermissionEffect       `protobuf:"varint,3,opt,name=effect,proto3,enum=service.v1.PermissionEffect" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionGrant) Reset() {
	*x = PermissionGrant{}
	mi := &file_api_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionGrant) ProtoMessage() {}

func (x *PermissionGrant) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionGrant.ProtoReflect.Descriptor instead.
func (*PermissionGrant) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{3}
}

func (x *PermissionGrant) GetTarget() *PermissionTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PermissionGrant) GetScope() *PermissionScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *PermissionGrant) GetEffect() PermissionEffect {
	if x != nil {
		return x.Effect
	}
	return PermissionEffect_PERMISSION_EFFECT_UNSPECIFIED
}

type PermissionTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTarget) Reset() {
	*x = PermissionTarget{}
	mi := &file_api_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTarget) ProtoMessage() {}

func (x *PermissionTarget) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTarget.ProtoReflect.Descriptor instead.
func (*PermissionTarget) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{4}
}

func (x *PermissionTarget) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *PermissionTarget) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *PermissionTarget) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type PermissionScope struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	GroupId        string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ObjectId       string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PermissionScope) Reset() {
	*x = PermissionScope{}
	mi := &file_api_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionScope) ProtoMessage() {}

func (x *PermissionScope) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionScope.ProtoReflect.Descriptor instead.
func (*PermissionScope) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{5}
}

func (x *PermissionScope) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *PermissionScope) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *PermissionScope) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaType     string                 `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Schema        *string                `protobuf:"bytes,2,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_api_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{6}
}

func (x *Payload) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Payload) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return ""
}

func (x *Payload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Attributes struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Values        map[string]*AttributeValues `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attributes) Reset() {
	*x = Attributes{}
	mi := &file_api_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attributes) ProtoMessage() {}

func (x *Attributes) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attributes.ProtoReflect.Descriptor instead.
func (*Attributes) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{7}
}

func (x *Attributes) GetValues() map[string]*AttributeValues {
	if x != nil {
		return x.Values
	}
	return nil
}

type AttributeValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValues) Reset() {
	*x = AttributeValues{}
	mi := &file_api_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValues) ProtoMessage() {}

func (x *AttributeValues) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValues.ProtoReflect.Descriptor instead.
func (*AttributeValues) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{8}
}

func (x *AttributeValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *Payload               `protobuf:"bytes,1,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	Attributes    *Attributes            `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_api_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{9}
}

func (x *InvokeResponse) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeResponse) GetAttributes() *Attributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_api_service_proto protoreflect.FileDescriptor

const file_api_service_proto_rawDesc = "" +
	"\n" +
	"\x11api/service.proto\x12\n" +
	"service.v1\"\xef\x01\n" +
	"\rInvokeRequest\x123\n" +
	"\toperation\x18\x01 \x01(\v2\x15.service.v1.OperationR\toperation\x121\n" +
	"\x06caller\x18\x02 \x01(\v2\x19.service.v1.CallerContextR\x06caller\x122\n" +
	"\apayload\x18\x03 \x01(\v2\x13.service.v1.PayloadH\x00R\apayload\x88\x01\x01\x126\n" +
	"\n" +
	"attributes\x18\x04 \x01(\v2\x16.service.v1.AttributesR\n" +
	"attributesB\n" +
	"\n" +
	"\b_payload\"\x1b\n" +
	"\tOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xad\x02\n" +
	"\rCallerContext\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12:\n" +
	"\fsubject_type\x18\x02 \x01(\x0e2\x17.service.v1.SubjectTypeR\vsubjectType\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tgroup_ids\x18\x04 \x03(\tR\bgroupIds\x123\n" +
	"\x06grants\x18\x05 \x03(\v2\x1b.service.v1.PermissionGrantR\x06grants\x120\n" +
	"\x11authentication_id\x18\x06 \x01(\tH\x00R\x10authenticationId\x88\x01\x01B\x14\n" +
	"\x12_authentication_id\"\xb0\x01\n" +
	"\x0fPermissionGrant\x124\n" +
	"\x06target\x18\x01 \x01(\v2\x1c.service.v1.PermissionTargetR\x06target\x121\n" +
	"\x05scope\x18\x02 \x01(\v2\x1b.service.v1.PermissionScopeR\x05scope\x124\n" +
	"\x06effect\x18\x03 \x01(\x0e2\x1c.service.v1.PermissionEffectR\x06effect\"g\n" +
	"\x10PermissionTarget\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"r\n" +
	"\x0fPermissionScope\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\"d\n" +
	"\aPayload\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x1b\n" +
	"\x06schema\x18\x02 \x01(\tH\x00R\x06schema\x88\x01\x01\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04dataB\t\n" +
	"\a_schema\"\xa0\x01\n" +
	"\n" +
	"Attributes\x12:\n" +
	"\x06values\x18\x01 \x03(\v2\".service.v1.Attributes.ValuesEntryR\x06values\x1aV\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.service.v1.AttributeValuesR\x05value:\x028\x01\")\n" +
	"\x0fAttributeValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x88\x01\n" +
	"\x0eInvokeResponse\x122\n" +
	"\apayload\x18\x01 \x01(\v2\x13.service.v1.PayloadH\x00R\apayload\x88\x01\x01\x126\n" +
	"\n" +
	"attributes\x18\x02 \x01(\v2\x16.service.v1.AttributesR\n" +
	"attributesB\n" +
	"\n" +
	"\b_payload*\x99\x01\n" +
	"\vSubjectType\x12\x1c\n" +
	"\x18SUBJECT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SUBJECT_TYPE_USER\x10\x01\x12 \n" +
	"\x1cSUBJECT_TYPE_SERVICE_ACCOUNT\x10\x02\x12\x17\n" +
	"\x13SUBJECT_TYPE_SYSTEM\x10\x03\x12\x1a\n" +
	"\x16SUBJECT_TYPE_ANONYMOUS\x10\x04*n\n" +
	"\x10PermissionEffect\x12!\n" +
	"\x1dPERMISSION_EFFECT_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PERMISSION_EFFECT_ALLOW\x10\x01\x12\x1a\n" +
	"\x16PERMISSION_EFFECT_DENY\x10\x022Q\n" +
	"\x0eBackendRuntime\x12?\n" +
	"\x06Invoke\x12\x19.service.v1.InvokeRequest\x1a\x1a.service.v1.InvokeResponseB0Z.github.com/infraconf/service-api/api;servicev1b\x06proto3"

var (
	file_api_service_proto_rawDescOnce sync.Once
	file_api_service_proto_rawDescData []byte
)

func file_api_service_proto_rawDescGZIP() []byte {
	file_api_service_proto_rawDescOnce.Do(func() {
		file_api_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_service_proto_rawDesc), len(file_api_service_proto_rawDesc)))
	})
	return file_api_service_proto_rawDescData
}

var file_api_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_service_proto_goTypes = []any{
	(SubjectType)(0),         // 0: service.v1.SubjectType
	(PermissionEffect)(0),    // 1: service.v1.PermissionEffect
	(*InvokeRequest)(nil),    // 2: service.v1.InvokeRequest
	(*Operation)(nil),        // 3: service.v1.Operation
	(*CallerContext)(nil),    // 4: service.v1.CallerContext
	(*PermissionGrant)(nil),  // 5: service.v1.PermissionGrant
	(*PermissionTarget)(nil), // 6: service.v1.PermissionTarget
	(*PermissionScope)(nil),  // 7: service.v1.PermissionScope
	(*Payload)(nil),          // 8: service.v1.Payload
	(*Attributes)(nil),       // 9: service.v1.Attributes
	(*AttributeValues)(nil),  // 10: service.v1.AttributeValues
	(*InvokeResponse)(nil),   // 11: service.v1.InvokeResponse
	nil,                      // 12: service.v1.Attributes.ValuesEntry
}
var file_api_service_proto_depIdxs = []int32{
	3,  // 0: service.v1.InvokeRequest.operation:type_name -> service.v1.Operation
	4,  // 1: service.v1.InvokeRequest.caller:type_name -> service.v1.CallerContext
	8,  // 2: service.v1.InvokeRequest.payload:type_name -> service.v1.Payload
	9,  // 3: service.v1.InvokeRequest.attributes:type_name -> service.v1.Attributes
	0,  // 4: service.v1.CallerContext.subject_type:type_name -> service.v1.SubjectType
	5,  // 5: service.v1.CallerContext.grants:type_name -> service.v1.PermissionGrant
	6,  // 6: service.v1.PermissionGrant.target:type_name -> service.v1.PermissionTarget
	7,  // 7: service.v1.PermissionGrant.scope:type_name -> service.v1.PermissionScope
	1,  // 8: service.v1.PermissionGrant.effect:type_name -> service.v1.PermissionEffect
	12, // 9: service.v1.Attributes.values:type_name -> service.v1.Attributes.ValuesEntry
	8,  // 10: service.v1.InvokeResponse.payload:type_name -> service.v1.Payload
	9,  // 11: service.v1.InvokeResponse.attributes:type_name -> service.v1.Attributes
	10, // 12: service.v1.Attributes.ValuesEntry.value:type_name -> service.v1.AttributeValues
	2,  // 13: service.v1.BackendRuntime.Invoke:input_type -> service.v1.InvokeRequest
	11, // 14: service.v1.BackendRuntime.Invoke:output_type -> service.v1.InvokeResponse
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_service_proto_init() }
func file_api_service_proto_init() {
	if File_api_service_proto != nil {
		return
	}
	file_api_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_service_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_service_proto_rawDesc), len(file_api_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service_proto_goTypes,
		DependencyIndexes: file_api_service_proto_depIdxs,
		EnumInfos:         file_api_service_proto_enumTypes,
		MessageInfos:      file_api_service_proto_msgTypes,
	}.Build()
	File_api_service_proto = out.File
	file_api_service_proto_goTypes = nil
	file_api_service_proto_depIdxs = nil
}
